<?php
require __DIR__ . '/lib/Auth.php';
Auth::requirePage();
require_once __DIR__ . '/config/db.php';
require_once __DIR__ . '/lib/Settings.php';

$id = (int) ($_GET['id'] ?? 0);
$st = db()->prepare('SELECT i.*, d.code AS driver_code, d.name AS driver_name
                     FROM incidents i LEFT JOIN drivers d ON d.id=i.driver_id WHERE i.id=?');
$st->execute([$id]);
$r = $st->fetch();
if (!$r) { http_response_code(404); exit('Incident not found.'); }
$mapsKey = Settings::get('google_maps_key');
function h($v){ return htmlspecialchars((string) $v); }
$staticMap = ($mapsKey && $r['lat'])
    ? 'https://maps.googleapis.com/maps/api/staticmap?center=' . $r['lat'] . ',' . $r['lng']
      . '&zoom=15&size=640x300&markers=color:red%7C' . $r['lat'] . ',' . $r['lng'] . '&key=' . urlencode($mapsKey)
    : '';
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Incident Report #<?= $id ?></title>
<style>
  *{box-sizing:border-box} body{font-family:'Segoe UI',Arial,sans-serif;color:#1f2937;margin:0;padding:32px;font-size:14px}
  .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #4f46e5;padding-bottom:14px;margin-bottom:20px}
  .head h1{margin:0;font-size:22px} .head .sub{color:#6b7280;font-size:13px}
  .org{text-align:right;font-weight:700} .org small{display:block;color:#6b7280;font-weight:400}
  .no{background:#4f46e5;color:#fff;padding:4px 12px;border-radius:6px;font-weight:700}
  table{width:100%;border-collapse:collapse;margin:10px 0}
  td,th{border:1px solid #d1d5db;padding:8px 10px;text-align:left;vertical-align:top}
  th{background:#f3f4f6;width:170px;font-weight:600}
  .sev{display:inline-block;padding:2px 10px;border-radius:12px;color:#fff;font-weight:600;font-size:12px}
  .map{margin-top:14px} .map img{width:100%;border:1px solid #d1d5db;border-radius:8px}
  .photo{max-width:420px;border:1px solid #d1d5db;border-radius:8px;margin-top:8px}
  .sign{display:flex;justify-content:space-between;margin-top:60px}
  .sign div{width:40%;border-top:1px solid #333;padding-top:6px;text-align:center;font-size:12px;color:#374151}
  .foot{margin-top:30px;color:#9ca3af;font-size:11px;text-align:center}
  @media print{ .noprint{display:none} body{padding:0} }
</style></head>
<body>
<?php
  $sevColors = ['low'=>'#22c55e','medium'=>'#f59e0b','high'=>'#f97316','critical'=>'#ef4444'];
?>
<div class="noprint" style="margin-bottom:14px">
  <button onclick="window.print()" style="padding:8px 16px;background:#4f46e5;color:#fff;border:none;border-radius:8px;cursor:pointer">🖨 Print</button>
  <a href="incidents.php" style="margin-left:8px">← Back</a>
</div>

<div class="head">
  <div><h1>Incident Report</h1><div class="sub">Reference: <span class="no">#<?= $id ?></span></div></div>
  <div class="org">Panabo Trucking Services<small>FleetIQ — GPS Monitoring</small></div>
</div>

<table>
  <tr><th>Date &amp; Time</th><td><?= h($r['incident_date']) ?></td></tr>
  <tr><th>Truck Code</th><td><?= h($r['truck_code'] ?: '—') ?></td></tr>
  <tr><th>Driver</th><td><?= h(trim(($r['driver_code'] ?? '') . ' ' . ($r['driver_name'] ?? ''))) ?: '—' ?></td></tr>
  <tr><th>Incident Type</th><td><?= h($r['itype']) ?></td></tr>
  <tr><th>Severity</th><td><span class="sev" style="background:<?= $sevColors[$r['severity']] ?? '#999' ?>"><?= strtoupper(h($r['severity'])) ?></span></td></tr>
  <tr><th>Status</th><td><?= ucfirst(h($r['status'])) ?></td></tr>
  <tr><th>Location</th><td><?= h($r['address'] ?: '—') ?><?= $r['lat'] ? ' (' . h($r['lat']) . ', ' . h($r['lng']) . ')' : '' ?></td></tr>
  <tr><th>Description</th><td><?= nl2br(h($r['description'] ?: '—')) ?></td></tr>
  <tr><th>Reported By</th><td><?= h($r['reported_by'] ?: '—') ?></td></tr>
</table>

<?php if ($staticMap): ?><div class="map"><img src="<?= h($staticMap) ?>" alt="Location map"></div><?php endif; ?>
<?php if ($r['photo']): ?><div><strong>Attached Photo:</strong><br><img class="photo" src="uploads/<?= h($r['photo']) ?>"></div><?php endif; ?>

<div class="sign">
  <div>Prepared By</div><div>Reviewed / Approved By</div>
</div>
<div class="foot">Generated by FleetIQ on <?= date('F d, Y h:i A') ?> · This is a system-generated incident report.</div>
</body></html>
